/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author thoar
 */
public class OptionDlg extends javax.swing.JDialog {

    /**
     * Creates new form OptionDlg
     */
    private LesJoueurs lj;
    private boolean ok;
    private int nc;
    
    public OptionDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lj = new LesJoueurs();
        ok = true;
        nc = 0;
    }
    
    public LesJoueurs getJoueurs(){return this.lj;}
    public boolean getOk(){return this.ok;}
    public int getNiveau(){return this.nc;}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Niv1 = new javax.swing.JRadioButton();
        Niv10 = new javax.swing.JRadioButton();
        Niv18 = new javax.swing.JRadioButton();
        Niv32 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        BPhoto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jPanel3.setLayout(new java.awt.GridLayout(5, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choisissez la taille du jeu");
        jPanel3.add(jLabel1);

        buttonGroup1.add(Niv1);
        Niv1.setText("enfant (4 personnages, 2 familles)");
        Niv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Niv1ActionPerformed(evt);
            }
        });
        jPanel3.add(Niv1);

        buttonGroup1.add(Niv10);
        Niv10.setText("débutant (10 personnages, 2 familles)");
        Niv10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Niv10ActionPerformed(evt);
            }
        });
        jPanel3.add(Niv10);

        buttonGroup1.add(Niv18);
        Niv18.setText("avancé (18 personnages, 4 familles)");
        Niv18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Niv18ActionPerformed(evt);
            }
        });
        jPanel3.add(Niv18);

        buttonGroup1.add(Niv32);
        Niv32.setText("expert (32 personnages, 6 familles)");
        Niv32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Niv32ActionPerformed(evt);
            }
        });
        jPanel3.add(Niv32);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(5, 1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Choisissez les joueurs créés par défaut");
        jPanel4.add(jLabel2);

        jCheckBox1.setText("Lara");
        jPanel4.add(jCheckBox1);

        jCheckBox2.setText("Jack");
        jPanel4.add(jCheckBox2);

        jCheckBox3.setText("Jean-Sébastien");
        jPanel4.add(jCheckBox3);

        jCheckBox4.setText("Amadeus");
        jPanel4.add(jCheckBox4);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(2, 1));

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        jPanel5.add(jScrollPane1);

        BPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lara.jpg"))); // NOI18N
        jPanel5.add(BPhoto);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel2.add(Annuler);

        Valider.setText("Valider");
        jPanel2.add(Valider);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
         this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_AnnulerActionPerformed

    private void Niv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Niv1ActionPerformed
       this.nc = 4;
    }//GEN-LAST:event_Niv1ActionPerformed

    private void Niv10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Niv10ActionPerformed
       this.nc = 10;
    }//GEN-LAST:event_Niv10ActionPerformed

    private void Niv18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Niv18ActionPerformed
        this.nc = 18;
    }//GEN-LAST:event_Niv18ActionPerformed

    private void Niv32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Niv32ActionPerformed
       this.nc = 32;
    }//GEN-LAST:event_Niv32ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OptionDlg dialog = new OptionDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JButton BPhoto;
    private javax.swing.JTextArea Edition;
    private javax.swing.JRadioButton Niv1;
    private javax.swing.JRadioButton Niv10;
    private javax.swing.JRadioButton Niv18;
    private javax.swing.JRadioButton Niv32;
    private javax.swing.JButton Valider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
