
import java.awt.Image;
import java.awt.Toolkit;
import java.io.*;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author unknown
 */

   
public class SaisieJoueurDlg extends javax.swing.JDialog {

    //déclaration des attributs de la classe
    private Joueur j;
    private boolean ok;
    private ImageIcon photo;
    private LesPersonnages lp;
    
    //Accesseurs des attributs
    public Joueur getJoueur(){return this.j;}
    public boolean getOk(){return this.ok;}

    /**
     * Creates new form SaisieJoueurDlg
     * @param parent
     * @param modal
     * @param lp
     */
    
    //Constructeur de la classe, prenant comme paramètre supplémentaire une liste de personnges lp
    public SaisieJoueurDlg(java.awt.Frame parent, boolean modal ,LesPersonnages lp) {
        super(parent, modal); //appel du constructeur de la classe mère
        initComponents();
        //Initialisation des attributs
        this.ok=false; 
        this.lp=lp;
        j = new Joueur();
        initListeFamilles(); //méthode pour remplir la JList avec les noms des familles, sans doublon
        this.ListeFamilles.setSelectedIndex(0); //sélection par défaut du premier élément de la JList
        
    }
    
    private void initListeFamilles(){
        DefaultListModel dlm = new DefaultListModel(); //déclaration d'une variable qui sera le modèle de la JList
        
        for(int i = 0; i<lp.getTaille();i++) //on parcourt la liste des personnages
        {
            String famille = lp.getPerso(i).getFamille(); //on récupère la famille du personnage en indice i de la liste
            boolean contient = false; //déclaration d'un booléen, qui permettra de vérifier les doublons
            for(int j=0;j<dlm.size();j++) //parcours du modèle
            {
                if(dlm.get(j).equals(famille)) //si le modèle contient déjà le nom de la famille, le booléen passe à true
                    contient=true;
            }
            
            if(contient==false)
            dlm.addElement(famille); //si le booléen est toujours à false, c'est-à-dire que le modèle ne contient pas déjà cette famille, on l'ajoute
        }
        this.ListeFamilles.setModel(dlm); //on applique le modèle à la JList
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_NORTH = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_WEST = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Pseudo = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListeFamilles = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Parcourir = new javax.swing.JButton();
        jPanel_CENTER = new javax.swing.JPanel();
        Photo = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jLabel1.setText("Créez votre joueur");
        jPanel_NORTH.add(jLabel1);

        getContentPane().add(jPanel_NORTH, java.awt.BorderLayout.NORTH);

        jPanel_WEST.setLayout(new java.awt.GridLayout(3, 1));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Donnez votre pseudo :");
        jPanel4.add(jLabel6, java.awt.BorderLayout.NORTH);

        Pseudo.setColumns(20);
        Pseudo.setRows(5);
        jScrollPane3.setViewportView(Pseudo);

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel_WEST.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Quelle est votre famille préférée des personnages : ");
        jPanel5.add(jLabel5, java.awt.BorderLayout.NORTH);

        jScrollPane4.setViewportView(ListeFamilles);

        jPanel5.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel_WEST.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Choisissez une photo :");
        jPanel6.add(jLabel7, java.awt.BorderLayout.NORTH);

        Parcourir.setText("Parcourir");
        Parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParcourirActionPerformed(evt);
            }
        });
        jPanel6.add(Parcourir, java.awt.BorderLayout.CENTER);

        jPanel_WEST.add(jPanel6);

        getContentPane().add(jPanel_WEST, java.awt.BorderLayout.WEST);

        jPanel_CENTER.setLayout(new java.awt.BorderLayout());
        jPanel_CENTER.add(Photo, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel7.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel7.add(Valider);

        jPanel_CENTER.add(jPanel7, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel_CENTER, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParcourirActionPerformed
        //On crée une variable
        JFileChooser jf= new JFileChooser();
        // Si un fichier a été choisi
        if (jf.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)
        {
            //On récupére le chemin d'acces à la photo
            String path = jf.getSelectedFile().getPath();
            //On récupére l'image dans l'ordi
            Image img=Toolkit.getDefaultToolkit().getImage(path);
            //On redimensionne la photo pour qu'elle prenne pas plus ni moins de place que le bouton Photo
            img=img.getScaledInstance(Photo.getWidth()-10, Photo.getHeight()-10, Image.SCALE_DEFAULT);
            //On construit l'ImageIcon à partir de l'image séléctionnée
            photo = new ImageIcon(img);
            //On met l'image sur le bouton
            Photo.setIcon(photo);
     } 
    }//GEN-LAST:event_ParcourirActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
       if(!this.Pseudo.getText().equals("")) //on vérifie qu'un pseudo a bien été saisi
       {
           if(this.ListeFamilles.getSelectedIndex()!=-1) //on vérifie qu'une valeur a bien été sélectionnée dans la liste
           {    
                //si les conditions précédentes sont réalisées, on crée un nouveau joueur avec le pseudo et la famille sélectionnée
                this.j = new Joueur(this.Pseudo.getText(),this.ListeFamilles.getSelectedValue());
                if(this.photo!=null) //si une photo a bien été sélectionnée
                {
                    j.setPhoto(photo); //on applique cette photo au joueur créé
                    this.setVisible(false); //on ferme la JDialog
                    this.dispose(); //fermeture de l'instance associée
                    this.ok=true; //on met le booléen à true, pour spécifier qu'un joueur a bien été créé
                }
           }
           else
           {
               //si aucune famille n'a été sélectionnée, on applique au joueur la première famille de la liste
               j.setFamillePref(this.ListeFamilles.getModel().getElementAt(0)); 
               
           }
       } 
       else
       {
           //si aucun pseudo n'a été rentré, on met un message d'erreur dans la JTextArea
           this.Pseudo.setText("Vous n'avez pas saisi de pseudo !!!");
       }
    }//GEN-LAST:event_ValiderActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        //si on clique sur le bouton Annuler de la JDialog, celle-ci se ferme et le booléen est mis à 0, pour indiquer qu'aucun joueur n'a été créé
        this.ok=false;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_AnnulerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JList<String> ListeFamilles;
    private javax.swing.JButton Parcourir;
    private javax.swing.JButton Photo;
    private javax.swing.JTextArea Pseudo;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_CENTER;
    private javax.swing.JPanel jPanel_NORTH;
    private javax.swing.JPanel jPanel_WEST;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}