
import java.awt.Image;
import java.awt.Toolkit;
import java.io.*;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author unknown
 */

   
public class SaisieJoueurDlg extends javax.swing.JDialog {

    
     private Joueur j;
     boolean ok;
     ImageIcon photo;
     LesPersonnages lp;
     
     public Joueur getJoueur()
     {
         return this.j;
     }
     public boolean getOk()
     {
         return this.ok;
     }
     
    /**
     * Creates new form SaisieJoueurDlg
     */
    public SaisieJoueurDlg(java.awt.Frame parent, boolean modal ,LesPersonnages lp) {
        super(parent, modal);
        initComponents();
        this.ok=false;
        this.lp=lp;
        initListeFamilles();
        
    }
    
    private void initListeFamilles(){
        DefaultListModel dlm = new DefaultListModel();
        for(int i = 0; i<lp.getTaille();i++)
        {
            dlm.addElement(lp.getPerso(i).getFamille());
        }
        this.ListeFamilles.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Pseudo = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListeFamilles = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Parcourir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Photo = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Créez votre joueur");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Donnez votre pseudo :");
        jPanel4.add(jLabel6, java.awt.BorderLayout.CENTER);

        Pseudo.setColumns(20);
        Pseudo.setRows(5);
        jScrollPane3.setViewportView(Pseudo);

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Quelle est votre famille préférée des personnages : ");
        jPanel5.add(jLabel5, java.awt.BorderLayout.NORTH);

        jScrollPane4.setViewportView(ListeFamilles);

        jPanel5.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Choisissez une photo :");
        jPanel6.add(jLabel7, java.awt.BorderLayout.NORTH);

        Parcourir.setText("Parcourir");
        Parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParcourirActionPerformed(evt);
            }
        });
        jPanel6.add(Parcourir, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(Photo, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel7.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel7.add(Valider);

        jPanel3.add(jPanel7, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParcourirActionPerformed
        //On crée une variable
        JFileChooser jf= new JFileChooser();
        // Si un fichier a été choisi
        if (jf.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)
        {
            //On récupére le chemin d'acces à la photo
            String path = jf.getSelectedFile().getPath();
            //On récupére l'mage dans l'ordi
            Image img=Toolkit.getDefaultToolkit().getImage(path);
            //On redimensionne la photo pour qu'elle prenne pas plus ni moins de place que le bouton Photo
            img=img.getScaledInstance(Photo.getWidth()-10, Photo.getHeight()-10, Image.SCALE_DEFAULT);
            //On costruit l'ImageIcon à partir de l'image séléctionnée
            photo = new ImageIcon(img);
            //On met l'image sur le bouton
            Photo.setIcon(photo);
     } 
    }//GEN-LAST:event_ParcourirActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
       if(this.Pseudo.getText()!= "")
       {
           if(this.ListeFamilles.getSelectedIndex()!=0)
           {
               
           
                this.j = new Joueur(this.Pseudo.getText(),this.ListeFamilles.getSelectedValue());
                if(this.photo!=null)
                {
                    this.Photo.setIcon(photo);
                    this.setVisible(false);
                    this.dispose();
                    this.ok=true;
                }
           }
       } 
       else
       {
           this.Pseudo.setText("Vous n'avez pas saisi de pseudo !!!");
       }
    }//GEN-LAST:event_ValiderActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        this.ok=false;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_AnnulerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JList<String> ListeFamilles;
    private javax.swing.JButton Parcourir;
    private javax.swing.JButton Photo;
    private javax.swing.JTextArea Pseudo;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}