
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author thoar
 */
public class VisuPersonnagesDlg extends javax.swing.JDialog {

    /**
     * Creates new form VisuPersonnagesDlg
     */
    private Joueur joueur;
    
    public VisuPersonnagesDlg(java.awt.Frame parent, boolean modal, Joueur joueur) {
        super(parent, modal);
        initComponents();
        //this.joueur = joueur;
        /*LesPersonnages p = new LesPersonnages(4);
        joueur = new Joueur("Lara", "epiques");
        this.joueur.setPhoto(new ImageIcon(getClass().getResource("/img/lara.jpg")));
        this.joueur.setPaquet(p);*/
        this.joueur = joueur;
        Joueur.setText("Cartes du joueur : "+this.joueur.getPseudo());
        Score.setText("Score : "+this.joueur.getScore());
        initPanneau();
    }
    
    public void initPanneau(){
        int taille = this.joueur.getPaquet().getTaille();
        trombinoscope.setLayout(new GridLayout(taille-1,taille-1));
        for(int i=0;i<this.joueur.getPaquet().getTaille();i++){
            JButton jb = new JButton();
            jb.setName("");
            trombinoscope.add(jb);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Joueur = new javax.swing.JLabel();
        Score = new javax.swing.JLabel();
        trombinoscope = new javax.swing.JPanel();
        Afficher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setLayout(new java.awt.BorderLayout());

        Joueur.setText("Cartes du joueur :");
        jPanel1.add(Joueur, java.awt.BorderLayout.NORTH);

        Score.setText("Score : ");
        jPanel1.add(Score, java.awt.BorderLayout.SOUTH);

        trombinoscope.setLayout(new java.awt.GridLayout(2, 2));
        jPanel1.add(trombinoscope, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        Afficher.setText("Afficher");
        Afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherActionPerformed(evt);
            }
        });
        getContentPane().add(Afficher, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<this.joueur.getPaquet().getTaille();i++){
            JButton jb = (JButton)trombinoscope.getComponent(i);
            Image imgperso = joueur.getPaquet().getPerso(i).getPhoto().getScaledInstance(jb.getWidth(),jb.getHeight(),Image.SCALE_SMOOTH);
            jb.setIcon(new ImageIcon(imgperso));
        }
    }//GEN-LAST:event_AfficherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnagesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnagesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnagesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnagesDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisuPersonnagesDlg dialog = new VisuPersonnagesDlg(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Afficher;
    private javax.swing.JLabel Joueur;
    private javax.swing.JLabel Score;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel trombinoscope;
    // End of variables declaration//GEN-END:variables
}
